name: Smoke test (Linux)
on: workflow_dispatch

jobs:
  unix:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare Jars for smoke testing
        run: |
          mkdir jars
          cd jars
          wget -q https://github.com/Cyolune/ip/releases/download/A-Release/sana.jar
          mv ../RepoSense.jar .

      - name: Perform smoke test
        run: python3 linux.py

      - name: Upload result as artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: linux.csv

  windows:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare Jars for smoke testing
        run: |
          New-Item jars -itemtype directory
          cd jars
          Invoke-WebRequest -OutFile sana.jar -Uri https://github.com/Cyolune/ip/releases/download/A-Release/sana.jar
          Move-Item -Path ..\RepoSense.jar -Destination .\RepoSense.jar

      - name: Perform smoke test
        run: python3 windows.py

      - name: Upload result as artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: windows.csv
