name: Smoke test (Linux)
on: [push, workflow_dispatch]

jobs:
  unix:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare Jars for smoke testing
        run: |
          mkdir jars
          cd jars
          wget -q https://github.com/Cyolune/ip/releases/download/A-Release/sana.jar
          mv ../RepoSense.jar .
          ls

      - name: Perform smoke test
        run: |
          Xvfb :99 &
          export DISPLAY=:99
          python3 linux.py

      - name: Upload result as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: linux.csv

      - name: Cleanup Xvfb
        uses: bcomnes/cleanup-xvfb@v1

  mac:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup headless environment
        run: brew install --cask xquartz

      - name: Prepare Jars for smoke testing
        run: |
          mkdir jars
          cd jars
          wget -q https://github.com/Cyolune/ip/releases/download/A-Release/sana.jar
          mv ../RepoSense.jar .
          ls

      - name: Perform smoke test
        run: |
          Xvfb :99 &
          export DISPLAY=:99
          python3 linux.py
          mv linux.csv mac.csv

      - name: Upload result as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: mac.csv

      - name: Cleanup Xvfb
        uses: bcomnes/cleanup-xvfb@v1

  windows:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare Jars for smoke testing
        run: |
          New-Item jars -itemtype directory
          cd jars
          Invoke-WebRequest -OutFile sana.jar -Uri https://github.com/Cyolune/ip/releases/download/A-Release/sana.jar
          Move-Item -Path ..\RepoSense.jar -Destination .\RepoSense.jar
          Get-ChildItem

      - name: Perform smoke test
        run: python3 windows.py

      - name: Upload result as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: windows.csv
