name: Smoke test (Mac and Windows)
on: [push, workflow_dispatch]

jobs:
  smoke:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      DISPLAY: :0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare Jars for smoke testing (Mac)
        if: runner.os == 'macOS'
        run: |
          mkdir jars
          cd jars
          wget -q https://github.com/Cyolune/ip/releases/download/A-Release/sana.jar
          mv ../RepoSense.jar .
          ls -lh

      - name: Prepare Jars for smoke testing (Windows)
        if: runner.os == 'Windows'
        run: |
          New-Item jars -itemtype directory
          cd jars
          Invoke-WebRequest -OutFile sana.jar -Uri https://github.com/Cyolune/ip/releases/download/A-Release/sana.jar
          Move-Item -Path ..\RepoSense.jar -Destination .\RepoSense.jar
          Get-ChildItem

      - name: Perform smoke test (Mac)
        if: runner.os == 'macOS'
        run: |
          system_profiler SPDisplaysDataType | grep Resolution
          python3 linux.py
          mv linux.csv ${{ runner.os }}.csv

      - name: Perform smoke test (Windows)
        if: runner.os == 'Windows'
        run: |
          Get-DisplayResolution
          python3 windows.py
          Move-Item -Path .\windows.csv -Destination .\${{ runner.os }}.csv

      - name: Upload result as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ runner.os }}.csv
